# Generated by Django 3.1.2 on 2021-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_post_venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.CharField(max_length=200, null=True)),
                ('Comprador', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('producto', models.CharField(max_length=200, null=True)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('region', models.CharField(max_length=200, null=True)),
                ('ciudad', models.CharField(max_length=200, null=True)),
                ('codigo_postal', models.CharField(max_length=200, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
