# Generated by Django 3.1.2 on 2021-05-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_post_venta', '0002_boleta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='precio',
            new_name='total',
        ),
        migrations.AddField(
            model_name='boleta',
            name='precio_unitario',
            field=models.FloatField(default=0),
        ),
    ]
