# Generated by Django 3.1.2 on 2021-06-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_post_venta', '0003_auto_20210518_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ordenitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordenitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='OrdenItem',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
