# Generated by Django 3.1.2 on 2021-06-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('num_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_cl', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('boletas', models.ManyToManyField(blank=True, related_name='clientes', to='orden_devolucion.Boleta')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='boletas', to='orden_devolucion.Producto'),
        ),
    ]
