# Generated by Django 3.1.2 on 2021-06-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden_devolucion', '0002_auto_20210612_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id',
            new_name='id_prod',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='productos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='num_telf',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemProducto',
            fields=[
                ('id_item', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_devolucion.producto')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='ItemProductos',
            field=models.ManyToManyField(blank=True, related_name='ItemProductos', to='orden_devolucion.ItemProducto'),
        ),
    ]
