# Generated by Django 3.1.2 on 2021-06-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_devolucion', '0003_auto_20210626_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='monto_dev',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='total_dev',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
