# Generated by Django 3.1.2 on 2021-06-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_devolucion', '0004_auto_20210626_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='monto_dev',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='total_dev',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
