# Generated by Django 3.1.2 on 2021-06-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_devolucion', '0005_auto_20210626_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproducto',
            name='productos',
        ),
        migrations.AddField(
            model_name='itemproducto',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='productos', to='orden_devolucion.Producto'),
        ),
    ]
