# Generated by Django 3.1.2 on 2021-06-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_devolucion', '0007_auto_20210627_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='itemProductos',
        ),
        migrations.AddField(
            model_name='boleta',
            name='ItemProductos',
            field=models.ManyToManyField(blank=True, related_name='ItemProductos', to='orden_devolucion.ItemProducto'),
        ),
    ]
